name: Update rates at end of day
on:
  workflow_dispatch:
    inputs:
      tags:
          description: 'Test scenario tags'  
  schedule:
    - cron: "0 0 * * *"

permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: writ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: execute py script # run main.py
        run: python ./bin/update_rates.py

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
